# Secret that can be used for deploying
# druid locally using local stack
# the secret deployed by druid is deployed in a
# non default namespace, thus this can be deployed
# in the default namespace
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: etcd-statefulset
    garden.sapcloud.io/role: controlplane
    role: main
  name: etcd-backup-aws
type: Opaque
data:
  accessKeyID: QUNDRVNTS0VZQVdTVVNFUg==
  bucketName: bXktYnVja2V0Cg==
  endpoint: aHR0cDovL2xvY2Fsc3RhY2suZGVmYXVsdDo0NTY2
  region: dXMtZWFzdC0y
  s3ForcePathStyle: dHJ1ZQ==
  secretAccessKey: c0VjcmVUS2V5
